sudo: required
dist: trusty
language: cpp
services:
  - docker
script:
  - "docker run -v $PWD:/mnt igankevich/fedora-meson sh -c 'cd /mnt; ./deploy/cibuild'"
  - "sudo chown -R $USER: build"
after_success:
  - "./deploy/cideploy"
branches:
  only:
  - master
